### ISSUE TITLE
Add Logout button on navbar menus

### ISSUE THREAD

**Issue by mosheeven** [tavorperry/MTA-Coffee#142]

**Comment by tavorperry** [comment]
I added logout button on navbar when the user is log-in. 
Else - there are "register" and "login" buttons.
![image](https://user-images.githubusercontent.com/18366738/49347354-52dcb480-f6a6-11e8-9d1a-7222b0965300.png)
![image](https://user-images.githubusercontent.com/18366738/49347358-5839ff00-f6a6-11e8-9889-a17afc44b4cb.png)
